spring.application.name=demo-spring-itmo
#spring.main.allow-bean-definition-overriding=true

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
## jdbc:postgresql://HOST:PORT/DBNAME
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

#Hibernate settings
# logging sql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ??? Hibernate ???????? ?? ??????
spring.jpa.hibernate.ddl-auto=validate